[tool.poetry]
name = "cicada"
version = "0.0.0"
description = "The Next Generation of CI/CD"
authors = ["dosisod"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/dosisod/cicada"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
  "Typing :: Typed"
]

[tool.poetry.dependencies]
python = ">=3.10"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
isort = "^5.10.1"
pytest = "^7.1.2"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
color_output = true
known_first_party = ["test"]

[tool.mypy]
namespace_packages = true
strict = true
disallow_any_decorated = true
disallow_any_explicit = true
disallow_any_unimported = true
warn_unreachable = true
allow_redefinition = true

[[tool.mypy.overrides]]
module = "test.*"
allow_untyped_defs = true

[tool.coverage.run]
omit = [
  # Just a bunch of abstract classes
  "cicada/api/repo/*",
  "cicada/api/logging.py",
  "cicada/api/infra/migrate.py",
  "cicada/api/__main__.py"
]

[tool.coverage.report]
exclude_lines = [
  "raise NotImplementedError\\(\\)",
  "pragma: no cover",
  "def __str__(self)",
  "assert False"
]
skip_covered = true
skip_empty = true

[tool.black]
line-length = 79
color = true

[tool.pytest.ini_options]
addopts = "--cov=cicada --cov-report=html --cov-report=term-missing --cov-fail-under=75"
asyncio_mode = "auto"
testpaths = ["test"]

[tool.ruff]
# TODO: enable FBT
extend-select = [
  "W", "N", "UP", "YTT", "S", "BLE", "B",
  "C4", "DTZ", "ISC", "PIE", "PT", "RET",
  "SIM", "PTH", "PLE", "RUF",
]
extend-ignore = ["F405", "N802", "N818", "S101", "B011", "PT012", "SIM102"]

[tool.ruff.per-file-ignores]
"cicada/parse/token.py" = ["E701"]
"cicada/api/*" = ["B008"]
"cicada/*" = ["PT"]
"test/ast/test_generate.py" = ["W293"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
