#!/bin/sh

pip install -r requirements.txt

# Wait for server to start before starting NGINX since Codespaces will auto
# open a page when port 80 is available, and we want to make sure the API is
# ready before then.
(
	sleep 1
	nginx -s stop &> /dev/null
	nginx
) &

# When stopping this script, continue and run migrations below
trap : SIGINT

python3 -m cicada.api

# Run migrations after server setup is complete because the autogenerated
# CICADA_ADMIN_PW env var won't be set until then.
python3 -m cicada.api.infra.migrate
